export const KEYCLOAK_REALM = import.meta.env.VITE_KEYCLOAK_REALM
export const KEYCLOAK_ID_CLIENT = import.meta.env.VITE_KEYCLOAK_ID_CLIENT
export const KEYCLOAK_CLIENT = import.meta.env.VITE_KEYCLOAK_CLIENT
export const KEYCLOAK_GROUP_PREFIX = import.meta.env.VITE_KEYCLOAK_GROUP_PREFIX
export const KEYCLOAK_ACCESS_GROUP = import.meta.env.VITE_KEYCLOAK_CLIENT_ACCESS_GROUP

export const ROLES = [
	'UAR_LIST',
	'UAR_UPDATE',
	'UAR_CREATE',
	'UAR_CHANGE_STATUS',
	'INSTRUMENT_LIST',
	'INSTRUMENT_UPDATE',
	'INSTRUMENT_CREATE',
	'INSTRUMENT_CHANGE_STATUS',
	'INSTRUMENT_CALIBRATION_LIST',
	'INSTRUMENT_CALIBRATION_UPDATE',
	'INSTRUMENT_CALIBRATION_CREATE',
	'INSTRUMENT_CALIBRATION_DELETE',
	'INSTRUMENT_READING_LIST',
	'INSTRUMENT_ENGINEERING_DATA_LIST',
	'INSTRUMENT_CHANNEL_LIST',
	'ALARM_LIST',
	'ALARM_COLOR_UPDATE',
	'AUTH_GROUP_LIST',
	'AUTH_GROUP_ASSIGN_ROLE',
	'AUTH_GROUP_REMOVE_ROLE',
	'AUTH_USER_LIST',
] as const
