import {
	barometerCalibrationFormSchema,
	barometerCalibrationSchema,
	directPendulumCalibrationFormSchema,
	directPendulumCalibrationSchema,
	electricJointMeterCalibrationFormSchema,
	electricJointMeterCalibrationSchema,
	extensometerCalibrationFormSchema,
	extensometerCalibrationSchema,
	flowMeterCalibrationFormSchema,
	flowMeterCalibrationSchema,
	geonorPiezometerCalibrationFormSchema,
	geonorPiezometerCalibrationSchema,
	invertedPendulumCalibrationFormSchema,
	invertedPendulumCalibrationSchema,
	standpipePiezometerCalibrationFormSchema,
	standpipePiezometerCalibrationSchema,
	strainMeterCalibrationFormSchema,
	strainMeterCalibrationSchema,
	stressMeterCalibrationFormSchema,
	stressMeterCalibrationSchema,
} from '@/schemas/calibration'
import {
	barometerReadingFormSchema,
	directPendulumReadingFormSchema,
	electricJointMeterReadingFormSchema,
	extensometerReadingFormSchema,
	flowMeterReadingFormSchema,
	geonorPiezometerReadingFormSchema,
	invertedPendulumReadingFormSchema,
	standpipePiezometerReadingFormSchema,
	strainMeterReadingFormSchema,
	stressMeterReadingFormSchema,
} from '@/schemas/reading'

export const instrumentTypeCalibrationFormSchemas = {
	BAROMETER: barometerCalibrationFormSchema,
	STRESS_METER: stressMeterCalibrationFormSchema,
	STRAIN_METER: strainMeterCalibrationFormSchema,
	DIRECT_PENDULUM: directPendulumCalibrationFormSchema,
	ELECTRIC_JOINT_METER: electricJointMeterCalibrationFormSchema,
	EXTENSOMETER: extensometerCalibrationFormSchema,
	FLOW_METER: flowMeterCalibrationFormSchema,
	GEONOR_PIEZOMETER: geonorPiezometerCalibrationFormSchema,
	INVERTED_PENDULUM: invertedPendulumCalibrationFormSchema,
	STANDPIPE_PIEZOMETER: standpipePiezometerCalibrationFormSchema,
}

export const instrumentTypeCalibrationSchemas = {
	BAROMETER: barometerCalibrationSchema,
	STRESS_METER: stressMeterCalibrationSchema,
	STRAIN_METER: strainMeterCalibrationSchema,
	DIRECT_PENDULUM: directPendulumCalibrationSchema,
	ELECTRIC_JOINT_METER: electricJointMeterCalibrationSchema,
	EXTENSOMETER: extensometerCalibrationSchema,
	FLOW_METER: flowMeterCalibrationSchema,
	GEONOR_PIEZOMETER: geonorPiezometerCalibrationSchema,
	INVERTED_PENDULUM: invertedPendulumCalibrationSchema,
	STANDPIPE_PIEZOMETER: standpipePiezometerCalibrationSchema,
}

export const instrumentTypeReadingFormSchemas = {
	BAROMETER: barometerReadingFormSchema,
	STRESS_METER: stressMeterReadingFormSchema,
	STRAIN_METER: strainMeterReadingFormSchema,
	DIRECT_PENDULUM: directPendulumReadingFormSchema,
	ELECTRIC_JOINT_METER: electricJointMeterReadingFormSchema,
	EXTENSOMETER: extensometerReadingFormSchema,
	FLOW_METER: flowMeterReadingFormSchema,
	GEONOR_PIEZOMETER: geonorPiezometerReadingFormSchema,
	INVERTED_PENDULUM: invertedPendulumReadingFormSchema,
	STANDPIPE_PIEZOMETER: standpipePiezometerReadingFormSchema,
	standpipePiezometerFormSchema: standpipePiezometerReadingFormSchema,
}
