export const INSTRUMENT_TYPES = [
	'BAROMETER',
	'STRESS_METER',
	'STRAIN_METER',
	'DIRECT_PENDULUM',
	'EXTENSOMETER',
	'ELECTRIC_JOINT_METER',
	'FLOW_METER',
	'GEONOR_PIEZOMETER',
	'INVERTED_PENDULUM',
	'STANDPIPE_PIEZOMETER',
] as const
